// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdNB05j6Lv67v5bgqh61Q44PCwd8VCofY',
    appId: '1:684043079706:web:ece28ea47ca662f46501a3',
    messagingSenderId: '684043079706',
    projectId: 'minima-do-384eb',
    authDomain: 'minima-do-384eb.firebaseapp.com',
    storageBucket: 'minima-do-384eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN8h4-T9jNBgiGp8pIae8rRXYR6IUFRic',
    appId: '1:684043079706:android:fb1b29c623a1ad776501a3',
    messagingSenderId: '684043079706',
    projectId: 'minima-do-384eb',
    storageBucket: 'minima-do-384eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_zRNLwv3xi30GVIDVbfQa2rr1HVP81cE',
    appId: '1:684043079706:ios:3d0d4e3da5a4aaa16501a3',
    messagingSenderId: '684043079706',
    projectId: 'minima-do-384eb',
    storageBucket: 'minima-do-384eb.appspot.com',
    iosBundleId: 'com.example.minimaDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_zRNLwv3xi30GVIDVbfQa2rr1HVP81cE',
    appId: '1:684043079706:ios:3d0d4e3da5a4aaa16501a3',
    messagingSenderId: '684043079706',
    projectId: 'minima-do-384eb',
    storageBucket: 'minima-do-384eb.appspot.com',
    iosBundleId: 'com.example.minimaDo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdNB05j6Lv67v5bgqh61Q44PCwd8VCofY',
    appId: '1:684043079706:web:8f3427c06f1b25826501a3',
    messagingSenderId: '684043079706',
    projectId: 'minima-do-384eb',
    authDomain: 'minima-do-384eb.firebaseapp.com',
    storageBucket: 'minima-do-384eb.appspot.com',
  );
}
